import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import joblib

print("Generating Data...")
np.random.seed(42)
n_samples = 5000

categories = ['Food & Dining', 'Groceries', 'Electronics', 'P2P Transfer', 'Utilities', 'Travel/Transport', 'Healthcare', 'Gaming/Entertainment']
devices = ['Mobile Web', 'Native App Android', 'Native App iOS', 'Desktop Web', 'POS Terminal']

data = {
    'transaction_hour': np.random.randint(0, 24, n_samples),
    'transaction_day': np.random.randint(1, 31, n_samples),
    'transaction_month': np.random.randint(1, 13, n_samples),
    'transaction_year': np.random.choice([2023, 2024], n_samples),
    'transaction_exact_time': np.random.randint(0, 86400, n_samples),
    'transaction_amount': np.random.exponential(scale=2000, size=n_samples),
    'upi_number': [f'upi{i}@bank' for i in range(n_samples)],
    'account_holder_name': [f'User{i}' for i in range(n_samples)],
    'seller_name': [f'Seller{np.random.randint(1, 100)}' for i in range(n_samples)],
    'transaction_category': np.random.choice(categories, n_samples),
    'device_type': np.random.choice(devices, p=[0.2, 0.4, 0.3, 0.05, 0.05], size=n_samples)
}

df = pd.DataFrame(data)

is_fraud = np.where(
    ((df['transaction_amount'] > 10000) & (df['transaction_hour'] < 5)) | 
    ((df['transaction_category'] == 'Gaming/Entertainment') & (df['transaction_amount'] > 5000)) | 
    ((df['transaction_category'] == 'P2P Transfer') & (df['transaction_amount'] > 20000)) | 
    ((df['device_type'] == 'Desktop Web') & (df['transaction_amount'] > 15000) & (df['transaction_hour'] > 22)), 1, 0
)

noise_indices = np.random.choice(df.index, size=int(n_samples * 0.05), replace=False)
is_fraud[noise_indices] = 1 - is_fraud[noise_indices]
df['transaction_status'] = np.where(is_fraud == 1, 'Fraud', 'Valid')
fail_indices = np.random.choice(df.index, size=int(n_samples * 0.05), replace=False)
df.loc[fail_indices, 'transaction_status'] = 'Failed'

print("Preprocessing...")
features_to_drop = ['upi_number', 'account_holder_name', 'seller_name']
df_filtered = df[df['transaction_status'] != 'Failed'].copy()
df_filtered['is_fraud'] = np.where(df_filtered['transaction_status'] == 'Fraud', 1, 0)
X = df_filtered.drop(columns=['is_fraud', 'transaction_status'] + features_to_drop)
y = df_filtered['is_fraud']

# Dynamically handle categorical variables to create training columns properly
X = pd.get_dummies(X, columns=['transaction_category', 'device_type'])

# IMPORTANT: Save the explicit list of columns generated by pandas so we can reproduce it in app.py
expected_columns = list(X.columns)
joblib.dump(expected_columns, 'expected_columns.pkl')

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print("Training Random Forest Classifier...")
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

acc = accuracy_score(y_test, rf_model.predict(X_test))
print(f"Random Forest Accuracy: {acc*100:.2f}%")

print("Saving models...")
joblib.dump(rf_model, 'rf_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
print("Model training and export complete.")
